ren "About.png" "About.png"
ren "Accounts.png" "Accounts.png"
ren "Address Book.png" "Address_Book.png"
ren "Air Brush.png" "Air_Brush.png"
ren "Align-Centre-2.png" "Align_Centre_2.png"
ren "Align-Centre.png" "Align_Centre.png"
ren "Align-Full-2.png" "Align_Full_2.png"
ren "Align-Full.png" "Align_Full.png"
ren "Align-Justify.png" "Align_Justify.png"
ren "Align-Left-2.png" "Align_Left_2.png"
ren "Align-Left.png" "Align_Left.png"
ren "Align-Right-2.png" "Align_Right_2.png"
ren "Align-Right.png" "Align_Right.png"
ren "Arrow-Left Right.png" "Arrow_Left_Right.png"
ren "Arrow-Up Down.png" "Arrow_Up_Down.png"
ren "Attachment.png" "Attachment.png"
ren "Auto Correct-Options.png" "Auto_Correct_Options.png"
ren "Auto-Type.png" "Auto_Type.png"
ren "Back.png" "Back.png"
ren "Bar Code.png" "Bar_Code.png"
ren "Bold-2.png" "Bold_2.png"
ren "Bold.png" "Bold.png"
ren "Book-Open.png" "Book_Open.png"
ren "Book-Search.png" "Book_Search.png"
ren "Books.png" "Books.png"
ren "Borders and Shading.png" "Borders_and_Shading.png"
ren "Box-Closed-2.png" "Box_Closed_2.png"
ren "Box-Closed.png" "Box_Closed.png"
ren "Box-Open-2.png" "Box_Open_2.png"
ren "Box-Open.png" "Box_Open.png"
ren "Bullets-2.png" "Bullets_2.png"
ren "Bullets.png" "Bullets.png"
ren "Calculator.png" "Calculator.png"
ren "Calendar-Go To Date.png" "Calendar_Go_To_Date.png"
ren "Calendar-Search.png" "Calendar_Search.png"
ren "Calendar-Select Day.png" "Calendar_Select_Day.png"
ren "Calendar-Select Month.png" "Calendar_Select_Month.png"
ren "Calendar-Select Week.png" "Calendar_Select_Week.png"
ren "Calendar-Select Work Week.png" "Calendar_Select_Work_Week.png"
ren "Calendar.png" "Calendar.png"
ren "Camera-Photo.png" "Camera_Photo.png"
ren "Camera.png" "Camera.png"
ren "Card File.png" "Card_File.png"
ren "Card-Add.png" "Card_Add.png"
ren "Card-Delete.png" "Card_Delete.png"
ren "Card-Edit.png" "Card_Edit.png"
ren "Card-New.png" "Card_New.png"
ren "Card-Next.png" "Card_Next.png"
ren "Card-Previous.png" "Card_Previous.png"
ren "Card-Remove.png" "Card_Remove.png"
ren "Card-Search.png" "Card_Search.png"
ren "Card.png" "Card.png"
ren "CD-Burn.png" "CD_Burn.png"
ren "CD-In Case.png" "CD_In_Case.png"
ren "CD-Rom.png" "CD_Rom.png"
ren "Center Across Cells.png" "Center_Across_Cells.png"
ren "Certificate.png" "Certificate.png"
ren "Chart-Bar.png" "Chart_Bar.png"
ren "Chart-Line.png" "Chart_Line.png"
ren "Chart-Pie.png" "Chart_Pie.png"
ren "Chart-Point.png" "Chart_Point.png"
ren "Chart.png" "Chart.png"
ren "Clean.png" "Clean.png"
ren "Clear.png" "Clear.png"
ren "Clipboard.png" "Clipboard.png"
ren "Clock.png" "Clock.png"
ren "Close.png" "Close.png"
ren "Colour Picker.png" "Colour_Picker.png"
ren "Columns-2.png" "Columns_2.png"
ren "Columns.png" "Columns.png"
ren "Command Prompt.png" "Command_Prompt.png"
ren "Compress.png" "Compress.png"
ren "Computer.png" "Computer.png"
ren "Connect.png" "Connect.png"
ren "Contact-Add.png" "Contact_Add.png"
ren "Contact-Delete.png" "Contact_Delete.png"
ren "Contact-Edit.png" "Contact_Edit.png"
ren "Contact-New.png" "Contact_New.png"
ren "Contact-Remove.png" "Contact_Remove.png"
ren "Contact-Search.png" "Contact_Search.png"
ren "Contact.png" "Contact.png"
ren "Copy.png" "Copy.png"
ren "Cross.png" "Cross.png"
ren "Currency-Notes.png" "Currency_Notes.png"
ren "Currency.png" "Currency.png"
ren "Cut.png" "Cut.png"
ren "Database-Add.png" "Database_Add.png"
ren "Database-Close.png" "Database_Close.png"
ren "Database-Delete.png" "Database_Delete.png"
ren "Database-Edit.png" "Database_Edit.png"
ren "Database-Filter.png" "Database_Filter.png"
ren "Database-New.png" "Database_New.png"
ren "Database-Open.png" "Database_Open.png"
ren "Database-Options.png" "Database_Options.png"
ren "Database-Properties.png" "Database_Properties.png"
ren "Database-Remove.png" "Database_Remove.png"
ren "Database-Save.png" "Database_Save.png"
ren "Database-Schema.png" "Database_Schema.png"
ren "Database-Search.png" "Database_Search.png"
ren "Database-Security.png" "Database_Security.png"
ren "Database-Wizard.png" "Database_Wizard.png"
ren "Database.png" "Database.png"
ren "Date-Time.png" "Date_Time.png"
ren "db-Add.png" "db_Add.png"
ren "db-Cancel.png" "db_Cancel.png"
ren "db-Delete.png" "db_Delete.png"
ren "db-Edit.png" "db_Edit.png"
ren "db-First.png" "db_First.png"
ren "db-Last.png" "db_Last.png"
ren "db-Next.png" "db_Next.png"
ren "db-Post.png" "db_Post.png"
ren "db-Previous.png" "db_Previous.png"
ren "db-Refresh.png" "db_Refresh.png"
ren "Decimals-Decrease.png" "Decimals_Decrease.png"
ren "Decimals-Increase-2.png" "Decimals_Increase_2.png"
ren "Decimals-Increase.png" "Decimals_Increase.png"
ren "Decompress.png" "Decompress.png"
ren "Delete-Blue.png" "Delete_Blue.png"
ren "Delete.png" "Delete.png"
ren "Design.png" "Design.png"
ren "Desktop.png" "Desktop.png"
ren "Dictionary.png" "Dictionary.png"
ren "Disconnect.png" "Disconnect.png"
ren "Discuss.png" "Discuss.png"
ren "Doc-Access.png" "Doc_Access.png"
ren "Doc-Acrobat.png" "Doc_Acrobat.png"
ren "Doc-Excel.png" "Doc_Excel.png"
ren "Doc-HTML.png" "Doc_HTML.png"
ren "Doc-Outlook.png" "Doc_Outlook.png"
ren "Doc-RTF.png" "Doc_RTF.png"
ren "Doc-Word.png" "Doc_Word.png"
ren "Doc-XML.png" "Doc_XML.png"
ren "Document-Auto Format.png" "Document_Auto_Format.png"
ren "Document-Protect.png" "Document_Protect.png"
ren "Drawing.png" "Drawing.png"
ren "Edit.png" "Edit.png"
ren "Equaliser.png" "Equaliser.png"
ren "Execute.png" "Execute.png"
ren "Exit.png" "Exit.png"
ren "Export-Access.png" "Export_Access.png"
ren "Export-Acrobat.png" "Export_Acrobat.png"
ren "Export-CSV.png" "Export_CSV.png"
ren "Export-Excel.png" "Export_Excel.png"
ren "Export-Fixed Length.png" "Export_Fixed_Length.png"
ren "Export-HTML.png" "Export_HTML.png"
ren "Export-Outlook.png" "Export_Outlook.png"
ren "Export-RTF.png" "Export_RTF.png"
ren "Export-Text.png" "Export_Text.png"
ren "Export-Word.png" "Export_Word.png"
ren "Export-XML.png" "Export_XML.png"
ren "Export.png" "Export.png"
ren "Favorites.png" "Favorites.png"
ren "Fill-Down.png" "Fill_Down.png"
ren "Fill-Left.png" "Fill_Left.png"
ren "Fill-Right.png" "Fill_Right.png"
ren "Fill-Up.png" "Fill_Up.png"
ren "Fill.png" "Fill.png"
ren "Filter.png" "Filter.png"
ren "Flag-Delete.png" "Flag_Delete.png"
ren "Flag-Next.png" "Flag_Next.png"
ren "Flag-Previous.png" "Flag_Previous.png"
ren "Flag.png" "Flag.png"
ren "Flow Chart.png" "Flow_Chart.png"
ren "Folder List.png" "Folder_List.png"
ren "Folder-Closed.png" "Folder_Closed.png"
ren "Folder-Delete.png" "Folder_Delete.png"
ren "Folder-New.png" "Folder_New.png"
ren "Folder-Options.png" "Folder_Options.png"
ren "Folder-Search.png" "Folder_Search.png"
ren "Folder.png" "Folder.png"
ren "Footer.png" "Footer.png"
ren "Format Font.png" "Format_Font.png"
ren "Format Painter.png" "Format_Painter.png"
ren "Format-Font Size.png" "Format_Font_Size.png"
ren "Format-Font.png" "Format_Font.png"
ren "Format-Paragraph-2.png" "Format_Paragraph_2.png"
ren "Format-Paragraph.png" "Format_Paragraph.png"
ren "Format-Percentage-2.png" "Format_Percentage_2.png"
ren "Format-Percentage.png" "Format_Percentage.png"
ren "Formatting-Remove.png" "Formatting_Remove.png"
ren "Forward.png" "Forward.png"
ren "Full Screen-New.png" "Full_Screen_New.png"
ren "Full Screen.png" "Full_Screen.png"
ren "Function-2.png" "Function_2.png"
ren "Function.png" "Function.png"
ren "Go To Line.png" "Go_To_Line.png"
ren "Grid Delete Column.png" "Grid_Delete_Column.png"
ren "Grid Delete Row-2.png" "Grid_Delete_Row_2.png"
ren "Grid Delete Row.png" "Grid_Delete_Row.png"
ren "Grid Insert Column To Left.png" "Grid_Insert_Column_To_Left.png"
ren "Grid Insert Column To Right.png" "Grid_Insert_Column_To_Right.png"
ren "Grid Insert Column.png" "Grid_Insert_Column.png"
ren "Grid Insert Row Above-2.png" "Grid_Insert_Row_Above_2.png"
ren "Grid Insert Row Above.png" "Grid_Insert_Row_Above.png"
ren "Grid Insert Row Below-2.png" "Grid_Insert_Row_Below_2.png"
ren "Grid Insert Row Below.png" "Grid_Insert_Row_Below.png"
ren "Grid Insert Row-2.png" "Grid_Insert_Row_2.png"
ren "Grid Insert Row.png" "Grid_Insert_Row.png"
ren "Grid-2.png" "Grid_2.png"
ren "Grid-Auto Format-2.png" "Grid_Auto_Format_2.png"
ren "Grid-Auto Format.png" "Grid_Auto_Format.png"
ren "Grid-Column Width.png" "Grid_Column_Width.png"
ren "Grid-Delete Cell.png" "Grid_Delete_Cell.png"
ren "Grid-Delete Column.png" "Grid_Delete_Column.png"
ren "Grid-Delete Row.png" "Grid_Delete_Row.png"
ren "Grid-Delete-2.png" "Grid_Delete_2.png"
ren "Grid-Delete.png" "Grid_Delete.png"
ren "Grid-Insert Cell.png" "Grid_Insert_Cell.png"
ren "Grid-Insert Column Left.png" "Grid_Insert_Column_Left.png"
ren "Grid-Insert Column Right.png" "Grid_Insert_Column_Right.png"
ren "Grid-Insert Column.png" "Grid_Insert_Column.png"
ren "Grid-Insert Row Above.png" "Grid_Insert_Row_Above.png"
ren "Grid-Insert Row Below.png" "Grid_Insert_Row_Below.png"
ren "Grid-Insert Row.png" "Grid_Insert_Row.png"
ren "Grid-Merge Cells.png" "Grid_Merge_Cells.png"
ren "Grid-New-2.png" "Grid_New_2.png"
ren "Grid-New.png" "Grid_New.png"
ren "Grid-Options-2.png" "Grid_Options_2.png"
ren "Grid-Options.png" "Grid_Options.png"
ren "Grid-Row Height.png" "Grid_Row_Height.png"
ren "Grid-Select All-2.png" "Grid_Select_All_2.png"
ren "Grid-Select All.png" "Grid_Select_All.png"
ren "Grid-Select Cell-2.png" "Grid_Select_Cell_2.png"
ren "Grid-Select Cell.png" "Grid_Select_Cell.png"
ren "Grid-Select Column-2.png" "Grid_Select_Column_2.png"
ren "Grid-Select Column.png" "Grid_Select_Column.png"
ren "Grid-Select Row-2.png" "Grid_Select_Row_2.png"
ren "Grid-Select Row.png" "Grid_Select_Row.png"
ren "Grid-Split Cells-2.png" "Grid_Split_Cells_2.png"
ren "Grid-Split Cells.png" "Grid_Split_Cells.png"
ren "Grid-Wizard-2.png" "Grid_Wizard_2.png"
ren "Grid-Wizard.png" "Grid_Wizard.png"
ren "Grid.png" "Grid.png"
ren "Hand Held.png" "Hand_Held.png"
ren "Hand Shake.png" "Hand_Shake.png"
ren "Header and Footer-Toggle.png" "Header_and_Footer_Toggle.png"
ren "Header and Footer.png" "Header_and_Footer.png"
ren "Header-Next.png" "Header_Next.png"
ren "Header-Previous.png" "Header_Previous.png"
ren "Header.png" "Header.png"
ren "Help.png" "Help.png"
ren "Highlighter.png" "Highlighter.png"
ren "History.png" "History.png"
ren "Home.png" "Home.png"
ren "Image-Brightness.png" "Image_Brightness.png"
ren "Image-Colour.png" "Image_Colour.png"
ren "Image-Contrast.png" "Image_Contrast.png"
ren "Image-Crop.png" "Image_Crop.png"
ren "Image-Flip.png" "Image_Flip.png"
ren "Image-Mirror.png" "Image_Mirror.png"
ren "Image-Paint.png" "Image_Paint.png"
ren "Image-Resize.png" "Image_Resize.png"
ren "Image-Rotate.png" "Image_Rotate.png"
ren "Image-Select.png" "Image_Select.png"
ren "Image.png" "Image.png"
ren "Import-Access.png" "Import_Access.png"
ren "Import-Acrobat.png" "Import_Acrobat.png"
ren "Import-CSV.png" "Import_CSV.png"
ren "Import-Excel.png" "Import_Excel.png"
ren "Import-Fixed Length.png" "Import_Fixed_Length.png"
ren "Import-HTML.png" "Import_HTML.png"
ren "Import-Outlook.png" "Import_Outlook.png"
ren "Import-RTF.png" "Import_RTF.png"
ren "Import-Text.png" "Import_Text.png"
ren "Import-Word.png" "Import_Word.png"
ren "Import-XML.png" "Import_XML.png"
ren "Import.png" "Import.png"
ren "Indent-Decrease-2.png" "Indent_Decrease_2.png"
ren "Indent-Decrease.png" "Indent_Decrease.png"
ren "Indent-Increase-2.png" "Indent_Increase_2.png"
ren "Indent-Increase.png" "Indent_Increase.png"
ren "Insert-File.png" "Insert_File.png"
ren "Insert-Image.png" "Insert_Image.png"
ren "Insert-Object.png" "Insert_Object.png"
ren "Insert.png" "Insert.png"
ren "Invoice.png" "Invoice.png"
ren "Italic-2.png" "Italic_2.png"
ren "Italic.png" "Italic.png"
ren "Key.png" "Key.png"
ren "Landscape.png" "Landscape.png"
ren "Launch.png" "Launch.png"
ren "Letter.png" "Letter.png"
ren "Line Spacing-2.png" "Line_Spacing_2.png"
ren "Line Spacing.png" "Line_Spacing.png"
ren "Link.png" "Link.png"
ren "list.txt" "list.txt"
ren "Lock.png" "Lock.png"
ren "Mail-Forward.png" "Mail_Forward.png"
ren "Mail-In Box-2.png" "Mail_In_Box_2.png"
ren "Mail-In Box.png" "Mail_In_Box.png"
ren "Mail-In-Out Box.png" "Mail_In_Out_Box.png"
ren "Mail-New.png" "Mail_New.png"
ren "Mail-Out Box-2.png" "Mail_Out_Box_2.png"
ren "Mail-Out Box.png" "Mail_Out_Box.png"
ren "Mail-Reply To All.png" "Mail_Reply_To_All.png"
ren "Mail-Reply.png" "Mail_Reply.png"
ren "Mail-Search.png" "Mail_Search.png"
ren "Mail-Send and Receive.png" "Mail_Send_and_Receive.png"
ren "Mail.png" "Mail.png"
ren "Media.png" "Media.png"
ren "Microphone.png" "Microphone.png"
ren "Midi Keyboard.png" "Midi_Keyboard.png"
ren "Minus.png" "Minus.png"
ren "mm-Eject.png" "mm_Eject.png"
ren "mm-Fast Forward.png" "mm_Fast_Forward.png"
ren "mm-First.png" "mm_First.png"
ren "mm-Last.png" "mm_Last.png"
ren "mm-Pause.png" "mm_Pause.png"
ren "mm-Play.png" "mm_Play.png"
ren "mm-Rewind.png" "mm_Rewind.png"
ren "mm-Stop.png" "mm_Stop.png"
ren "Monitor.png" "Monitor.png"
ren "Movie.png" "Movie.png"
ren "Musical Note-2.png" "Musical_Note_2.png"
ren "Musical Note.png" "Musical_Note.png"
ren "New.png" "New.png"
ren "Note-Add.png" "Note_Add.png"
ren "Note-Delete.png" "Note_Delete.png"
ren "Note-Edit.png" "Note_Edit.png"
ren "Note-New.png" "Note_New.png"
ren "Note-Next.png" "Note_Next.png"
ren "Note-Previous.png" "Note_Previous.png"
ren "Note-Remove.png" "Note_Remove.png"
ren "Note-Search.png" "Note_Search.png"
ren "Note.png" "Note.png"
ren "Notepad.png" "Notepad.png"
ren "Notes.png" "Notes.png"
ren "Number of Pages.png" "Number_of_Pages.png"
ren "Numbering-2.png" "Numbering_2.png"
ren "Numbering.png" "Numbering.png"
ren "Object-Bring To Front.png" "Object_Bring_To_Front.png"
ren "Object-Select.png" "Object_Select.png"
ren "Object-Send To Back.png" "Object_Send_To_Back.png"
ren "Open.png" "Open.png"
ren "Outline-2.png" "Outline_2.png"
ren "Outline.png" "Outline.png"
ren "Page Number.png" "Page_Number.png"
ren "Page-Break.png" "Page_Break.png"
ren "Page-Invert.png" "Page_Invert.png"
ren "Page-Next.png" "Page_Next.png"
ren "Page-Previous.png" "Page_Previous.png"
ren "Page-Setup.png" "Page_Setup.png"
ren "Paintbrush.png" "Paintbrush.png"
ren "Parcel.png" "Parcel.png"
ren "Paste.png" "Paste.png"
ren "Permission.png" "Permission.png"
ren "Phone.png" "Phone.png"
ren "Planner.png" "Planner.png"
ren "Plus.png" "Plus.png"
ren "Portrait.png" "Portrait.png"
ren "Preview.png" "Preview.png"
ren "Print-2.png" "Print_2.png"
ren "Print-Options-2.png" "Print_Options_2.png"
ren "Print-Options.png" "Print_Options.png"
ren "Print.png" "Print.png"
ren "Procedure.png" "Procedure.png"
ren "Process.png" "Process.png"
ren "Project-Gant Chart.png" "Project_Gant_Chart.png"
ren "Project.png" "Project.png"
ren "Properties.png" "Properties.png"
ren "Push Pin.png" "Push_Pin.png"
ren "Recycle Bin.png" "Recycle_Bin.png"
ren "Redo.png" "Redo.png"
ren "Refresh.png" "Refresh.png"
ren "Remove.png" "Remove.png"
ren "Rename.png" "Rename.png"
ren "Report-2.png" "Report_2.png"
ren "Report-Bound.png" "Report_Bound.png"
ren "Report.png" "Report.png"
ren "Research.png" "Research.png"
ren "Ruler-Formatting.png" "Ruler_Formatting.png"
ren "Ruler.png" "Ruler.png"
ren "Save All.png" "Save_All.png"
ren "Save As HTML.png" "Save_As_HTML.png"
ren "Save As.png" "Save_As.png"
ren "Save Draft.png" "Save_Draft.png"
ren "Save.png" "Save.png"
ren "Script.png" "Script.png"
ren "Search-Next.png" "Search_Next.png"
ren "Search-Previous.png" "Search_Previous.png"
ren "Search-Replace.png" "Search_Replace.png"
ren "Search.png" "Search.png"
ren "Select All-2.png" "Select_All_2.png"
ren "Select All.png" "Select_All.png"
ren "Selection-None.png" "Selection_None.png"
ren "Slide Show.png" "Slide_Show.png"
ren "Slide.png" "Slide.png"
ren "Software-Analyse.png" "Software_Analyse.png"
ren "Sort Ascending.png" "Sort_Ascending.png"
ren "Sort Descending.png" "Sort_Descending.png"
ren "Sort-Ascending.png" "Sort_Ascending.png"
ren "Sort-Descending.png" "Sort_Descending.png"
ren "Sound-Delete.png" "Sound_Delete.png"
ren "Sound-Fade In.png" "Sound_Fade_In.png"
ren "Sound-Fade Out.png" "Sound_Fade_Out.png"
ren "Sound-Join.png" "Sound_Join.png"
ren "Sound-Mark End.png" "Sound_Mark_End.png"
ren "Sound-Mark Start.png" "Sound_Mark_Start.png"
ren "Sound-Split.png" "Sound_Split.png"
ren "Spell Check.png" "Spell_Check.png"
ren "Stop.png" "Stop.png"
ren "Strikeout-2.png" "Strikeout_2.png"
ren "Strikeout.png" "Strikeout.png"
ren "Subscript-2.png" "Subscript_2.png"
ren "Subscript.png" "Subscript.png"
ren "Sum-2.png" "Sum_2.png"
ren "Sum.png" "Sum.png"
ren "Summary.png" "Summary.png"
ren "Superscript-2.png" "Superscript_2.png"
ren "Superscript.png" "Superscript.png"
ren "Support.png" "Support.png"
ren "Tables and Borders.png" "Tables_and_Borders.png"
ren "Task-Search.png" "Task_Search.png"
ren "Task.png" "Task.png"
ren "Thesaurus.png" "Thesaurus.png"
ren "Tick.png" "Tick.png"
ren "Time Line.png" "Time_Line.png"
ren "Tip.png" "Tip.png"
ren "To Do List.png" "To_Do_List.png"
ren "To Lowercase.png" "To_Lowercase.png"
ren "To Uppercase.png" "To_Uppercase.png"
ren "Tools.png" "Tools.png"
ren "Tree View-Add.png" "Tree_View_Add.png"
ren "Tree View-Delete.png" "Tree_View_Delete.png"
ren "Tree View-Edit.png" "Tree_View_Edit.png"
ren "Tree View-New.png" "Tree_View_New.png"
ren "Tree View-Remove.png" "Tree_View_Remove.png"
ren "Tree View-Search.png" "Tree_View_Search.png"
ren "Tree View.png" "Tree_View.png"
ren "Underline-2.png" "Underline_2.png"
ren "Underline.png" "Underline.png"
ren "Undo.png" "Undo.png"
ren "Unlock.png" "Unlock.png"
ren "User-2.png" "User_2.png"
ren "User-Add-2.png" "User_Add_2.png"
ren "User-Add.png" "User_Add.png"
ren "User-Delete-2.png" "User_Delete_2.png"
ren "User-Delete.png" "User_Delete.png"
ren "User-Edit-2.png" "User_Edit_2.png"
ren "User-Edit.png" "User_Edit.png"
ren "User-New-2.png" "User_New_2.png"
ren "User-New.png" "User_New.png"
ren "User-Options-2.png" "User_Options_2.png"
ren "User-Options.png" "User_Options.png"
ren "User-Password-2.png" "User_Password_2.png"
ren "User-Password.png" "User_Password.png"
ren "User-Remove-2.png" "User_Remove_2.png"
ren "User-Remove.png" "User_Remove.png"
ren "User-Search-2.png" "User_Search_2.png"
ren "User-Search.png" "User_Search.png"
ren "User-Security-2.png" "User_Security_2.png"
ren "User-Security.png" "User_Security.png"
ren "User.png" "User.png"
ren "Users-2.png" "Users_2.png"
ren "Users.png" "Users.png"
ren "View-Details.png" "View_Details.png"
ren "View-Large Icons.png" "View_Large_Icons.png"
ren "View-List.png" "View_List.png"
ren "View-One Page.png" "View_One_Page.png"
ren "View-Page Width.png" "View_Page_Width.png"
ren "View-Small Icons.png" "View_Small_Icons.png"
ren "Views.png" "Views.png"
ren "Volume-Mute.png" "Volume_Mute.png"
ren "Volume.png" "Volume.png"
ren "Warning.png" "Warning.png"
ren "Waste Bin.png" "Waste_Bin.png"
ren "Window-Add.png" "Window_Add.png"
ren "Window-Bring To Front.png" "Window_Bring_To_Front.png"
ren "Window-Cascade.png" "Window_Cascade.png"
ren "Window-Close.png" "Window_Close.png"
ren "Window-Delete.png" "Window_Delete.png"
ren "Window-Edit.png" "Window_Edit.png"
ren "Window-Maximise.png" "Window_Maximise.png"
ren "Window-Minimise.png" "Window_Minimise.png"
ren "Window-New.png" "Window_New.png"
ren "Window-Next.png" "Window_Next.png"
ren "Window-Options.png" "Window_Options.png"
ren "Window-Preview.png" "Window_Preview.png"
ren "Window-Previous.png" "Window_Previous.png"
ren "Window-Properties.png" "Window_Properties.png"
ren "Window-Remove.png" "Window_Remove.png"
ren "Window-Search.png" "Window_Search.png"
ren "Window-Send To Back.png" "Window_Send_To_Back.png"
ren "Window-Split.png" "Window_Split.png"
ren "Window-Tile Horizontal.png" "Window_Tile_Horizontal.png"
ren "Window-Tile Vertical.png" "Window_Tile_Vertical.png"
ren "Window.png" "Window.png"
ren "Wizard.png" "Wizard.png"
ren "Word Count.png" "Word_Count.png"
ren "Word Wrap-2.png" "Word_Wrap_2.png"
ren "Word Wrap.png" "Word_Wrap.png"
ren "Work Sheet-Auto Format.png" "Work_Sheet_Auto_Format.png"
ren "Work Sheet-Delete.png" "Work_Sheet_Delete.png"
ren "Work Sheet-New.png" "Work_Sheet_New.png"
ren "Work Sheet-Options.png" "Work_Sheet_Options.png"
ren "Work Sheet-Protect.png" "Work_Sheet_Protect.png"
ren "Work Sheet-Rename.png" "Work_Sheet_Rename.png"
ren "Work Sheet.png" "Work_Sheet.png"
ren "Zoom-In.png" "Zoom_In.png"
ren "Zoom-Out.png" "Zoom_Out.png"
