ren "About.png" "About_disabled.png"
ren "Accounts.png" "Accounts_disabled.png"
ren "Address Book.png" "Address_Book_disabled.png"
ren "Air Brush.png" "Air_Brush_disabled.png"
ren "Align-Centre-2.png" "Align_Centre_2_disabled.png"
ren "Align-Centre.png" "Align_Centre_disabled.png"
ren "Align-Full-2.png" "Align_Full_2_disabled.png"
ren "Align-Full.png" "Align_Full_disabled.png"
ren "Align-Justify.png" "Align_Justify_disabled.png"
ren "Align-Left-2.png" "Align_Left_2_disabled.png"
ren "Align-Left.png" "Align_Left_disabled.png"
ren "Align-Right-2.png" "Align_Right_2_disabled.png"
ren "Align-Right.png" "Align_Right_disabled.png"
ren "Arrow-Left Right.png" "Arrow_Left_Right_disabled.png"
ren "Arrow-Up Down.png" "Arrow_Up_Down_disabled.png"
ren "Attachment.png" "Attachment_disabled.png"
ren "Auto Correct-Options.png" "Auto_Correct_Options_disabled.png"
ren "Auto-Type.png" "Auto_Type_disabled.png"
ren "Back.png" "Back_disabled.png"
ren "Bar Code.png" "Bar_Code_disabled.png"
ren "Bold-2.png" "Bold_2_disabled.png"
ren "Bold.png" "Bold_disabled.png"
ren "Book-Open.png" "Book_Open_disabled.png"
ren "Book-Search.png" "Book_Search_disabled.png"
ren "Books.png" "Books_disabled.png"
ren "Borders and Shading.png" "Borders_and_Shading_disabled.png"
ren "Box-Closed-2.png" "Box_Closed_2_disabled.png"
ren "Box-Closed.png" "Box_Closed_disabled.png"
ren "Box-Open-2.png" "Box_Open_2_disabled.png"
ren "Box-Open.png" "Box_Open_disabled.png"
ren "Bullets-2.png" "Bullets_2_disabled.png"
ren "Bullets.png" "Bullets_disabled.png"
ren "Calculator.png" "Calculator_disabled.png"
ren "Calendar-Go To Date.png" "Calendar_Go_To_Date_disabled.png"
ren "Calendar-Search.png" "Calendar_Search_disabled.png"
ren "Calendar-Select Day.png" "Calendar_Select_Day_disabled.png"
ren "Calendar-Select Month.png" "Calendar_Select_Month_disabled.png"
ren "Calendar-Select Week.png" "Calendar_Select_Week_disabled.png"
ren "Calendar-Select Work Week.png" "Calendar_Select_Work_Week_disabled.png"
ren "Calendar.png" "Calendar_disabled.png"
ren "Camera-Photo.png" "Camera_Photo_disabled.png"
ren "Camera.png" "Camera_disabled.png"
ren "Card File.png" "Card_File_disabled.png"
ren "Card-Add.png" "Card_Add_disabled.png"
ren "Card-Delete.png" "Card_Delete_disabled.png"
ren "Card-Edit.png" "Card_Edit_disabled.png"
ren "Card-New.png" "Card_New_disabled.png"
ren "Card-Next.png" "Card_Next_disabled.png"
ren "Card-Previous.png" "Card_Previous_disabled.png"
ren "Card-Remove.png" "Card_Remove_disabled.png"
ren "Card-Search.png" "Card_Search_disabled.png"
ren "Card.png" "Card_disabled.png"
ren "CD-Burn.png" "CD_Burn_disabled.png"
ren "CD-In Case.png" "CD_In_Case_disabled.png"
ren "CD-Rom.png" "CD_Rom_disabled.png"
ren "Center Across Cells.png" "Center_Across_Cells_disabled.png"
ren "Certificate.png" "Certificate_disabled.png"
ren "Chart-Bar.png" "Chart_Bar_disabled.png"
ren "Chart-Line.png" "Chart_Line_disabled.png"
ren "Chart-Pie.png" "Chart_Pie_disabled.png"
ren "Chart-Point.png" "Chart_Point_disabled.png"
ren "Chart.png" "Chart_disabled.png"
ren "Clean.png" "Clean_disabled.png"
ren "Clear.png" "Clear_disabled.png"
ren "Clipboard.png" "Clipboard_disabled.png"
ren "Clock.png" "Clock_disabled.png"
ren "Close.png" "Close_disabled.png"
ren "Colour Picker.png" "Colour_Picker_disabled.png"
ren "Columns-2.png" "Columns_2_disabled.png"
ren "Columns.png" "Columns_disabled.png"
ren "Command Prompt.png" "Command_Prompt_disabled.png"
ren "Compress.png" "Compress_disabled.png"
ren "Computer.png" "Computer_disabled.png"
ren "Connect.png" "Connect_disabled.png"
ren "Contact-Add.png" "Contact_Add_disabled.png"
ren "Contact-Delete.png" "Contact_Delete_disabled.png"
ren "Contact-Edit.png" "Contact_Edit_disabled.png"
ren "Contact-New.png" "Contact_New_disabled.png"
ren "Contact-Remove.png" "Contact_Remove_disabled.png"
ren "Contact-Search.png" "Contact_Search_disabled.png"
ren "Contact.png" "Contact_disabled.png"
ren "Copy.png" "Copy_disabled.png"
ren "Cross.png" "Cross_disabled.png"
ren "Currency-Notes.png" "Currency_Notes_disabled.png"
ren "Currency.png" "Currency_disabled.png"
ren "Cut.png" "Cut_disabled.png"
ren "Database-Add.png" "Database_Add_disabled.png"
ren "Database-Close.png" "Database_Close_disabled.png"
ren "Database-Delete.png" "Database_Delete_disabled.png"
ren "Database-Edit.png" "Database_Edit_disabled.png"
ren "Database-Filter.png" "Database_Filter_disabled.png"
ren "Database-New.png" "Database_New_disabled.png"
ren "Database-Open.png" "Database_Open_disabled.png"
ren "Database-Options.png" "Database_Options_disabled.png"
ren "Database-Properties.png" "Database_Properties_disabled.png"
ren "Database-Remove.png" "Database_Remove_disabled.png"
ren "Database-Save.png" "Database_Save_disabled.png"
ren "Database-Schema.png" "Database_Schema_disabled.png"
ren "Database-Search.png" "Database_Search_disabled.png"
ren "Database-Security.png" "Database_Security_disabled.png"
ren "Database-Wizard.png" "Database_Wizard_disabled.png"
ren "Database.png" "Database_disabled.png"
ren "Date-Time.png" "Date_Time_disabled.png"
ren "db-Add.png" "db_Add_disabled.png"
ren "db-Cancel.png" "db_Cancel_disabled.png"
ren "db-Delete.png" "db_Delete_disabled.png"
ren "db-Edit.png" "db_Edit_disabled.png"
ren "db-First.png" "db_First_disabled.png"
ren "db-Last.png" "db_Last_disabled.png"
ren "db-Next.png" "db_Next_disabled.png"
ren "db-Post.png" "db_Post_disabled.png"
ren "db-Previous.png" "db_Previous_disabled.png"
ren "db-Refresh.png" "db_Refresh_disabled.png"
ren "Decimals-Decrease.png" "Decimals_Decrease_disabled.png"
ren "Decimals-Increase-2.png" "Decimals_Increase_2_disabled.png"
ren "Decimals-Increase.png" "Decimals_Increase_disabled.png"
ren "Decompress.png" "Decompress_disabled.png"
ren "Delete-Blue.png" "Delete_Blue_disabled.png"
ren "Delete.png" "Delete_disabled.png"
ren "Design.png" "Design_disabled.png"
ren "Desktop.png" "Desktop_disabled.png"
ren "Dictionary.png" "Dictionary_disabled.png"
ren "Disconnect.png" "Disconnect_disabled.png"
ren "Discuss.png" "Discuss_disabled.png"
ren "Doc-Access.png" "Doc_Access_disabled.png"
ren "Doc-Acrobat.png" "Doc_Acrobat_disabled.png"
ren "Doc-Excel.png" "Doc_Excel_disabled.png"
ren "Doc-HTML.png" "Doc_HTML_disabled.png"
ren "Doc-Outlook.png" "Doc_Outlook_disabled.png"
ren "Doc-RTF.png" "Doc_RTF_disabled.png"
ren "Doc-Word.png" "Doc_Word_disabled.png"
ren "Doc-XML.png" "Doc_XML_disabled.png"
ren "Document-Auto Format.png" "Document_Auto_Format_disabled.png"
ren "Document-Protect.png" "Document_Protect_disabled.png"
ren "Drawing.png" "Drawing_disabled.png"
ren "Edit.png" "Edit_disabled.png"
ren "Equaliser.png" "Equaliser_disabled.png"
ren "Execute.png" "Execute_disabled.png"
ren "Exit.png" "Exit_disabled.png"
ren "Export-Access.png" "Export_Access_disabled.png"
ren "Export-Acrobat.png" "Export_Acrobat_disabled.png"
ren "Export-CSV.png" "Export_CSV_disabled.png"
ren "Export-Excel.png" "Export_Excel_disabled.png"
ren "Export-Fixed Length.png" "Export_Fixed_Length_disabled.png"
ren "Export-HTML.png" "Export_HTML_disabled.png"
ren "Export-Outlook.png" "Export_Outlook_disabled.png"
ren "Export-RTF.png" "Export_RTF_disabled.png"
ren "Export-Text.png" "Export_Text_disabled.png"
ren "Export-Word.png" "Export_Word_disabled.png"
ren "Export-XML.png" "Export_XML_disabled.png"
ren "Export.png" "Export_disabled.png"
ren "Favorites.png" "Favorites_disabled.png"
ren "Fill-Down.png" "Fill_Down_disabled.png"
ren "Fill-Left.png" "Fill_Left_disabled.png"
ren "Fill-Right.png" "Fill_Right_disabled.png"
ren "Fill-Up.png" "Fill_Up_disabled.png"
ren "Fill.png" "Fill_disabled.png"
ren "Filter.png" "Filter_disabled.png"
ren "Flag-Delete.png" "Flag_Delete_disabled.png"
ren "Flag-Next.png" "Flag_Next_disabled.png"
ren "Flag-Previous.png" "Flag_Previous_disabled.png"
ren "Flag.png" "Flag_disabled.png"
ren "Flow Chart.png" "Flow_Chart_disabled.png"
ren "Folder List.png" "Folder_List_disabled.png"
ren "Folder-Closed.png" "Folder_Closed_disabled.png"
ren "Folder-Delete.png" "Folder_Delete_disabled.png"
ren "Folder-New.png" "Folder_New_disabled.png"
ren "Folder-Options.png" "Folder_Options_disabled.png"
ren "Folder-Search.png" "Folder_Search_disabled.png"
ren "Folder.png" "Folder_disabled.png"
ren "Footer.png" "Footer_disabled.png"
ren "Format Font.png" "Format_Font_disabled.png"
ren "Format Painter.png" "Format_Painter_disabled.png"
ren "Format-Font Size.png" "Format_Font_Size_disabled.png"
ren "Format-Font.png" "Format_Font_disabled.png"
ren "Format-Paragraph-2.png" "Format_Paragraph_2_disabled.png"
ren "Format-Paragraph.png" "Format_Paragraph_disabled.png"
ren "Format-Percentage-2.png" "Format_Percentage_2_disabled.png"
ren "Format-Percentage.png" "Format_Percentage_disabled.png"
ren "Formatting-Remove.png" "Formatting_Remove_disabled.png"
ren "Forward.png" "Forward_disabled.png"
ren "Full Screen-New.png" "Full_Screen_New_disabled.png"
ren "Full Screen.png" "Full_Screen_disabled.png"
ren "Function-2.png" "Function_2_disabled.png"
ren "Function.png" "Function_disabled.png"
ren "Go To Line.png" "Go_To_Line_disabled.png"
ren "Grid Delete Column.png" "Grid_Delete_Column_disabled.png"
ren "Grid Delete Row-2.png" "Grid_Delete_Row_2_disabled.png"
ren "Grid Delete Row.png" "Grid_Delete_Row_disabled.png"
ren "Grid Insert Column To Left.png" "Grid_Insert_Column_To_Left_disabled.png"
ren "Grid Insert Column To Right.png" "Grid_Insert_Column_To_Right_disabled.png"
ren "Grid Insert Column.png" "Grid_Insert_Column_disabled.png"
ren "Grid Insert Row Above-2.png" "Grid_Insert_Row_Above_2_disabled.png"
ren "Grid Insert Row Above.png" "Grid_Insert_Row_Above_disabled.png"
ren "Grid Insert Row Below-2.png" "Grid_Insert_Row_Below_2_disabled.png"
ren "Grid Insert Row Below.png" "Grid_Insert_Row_Below_disabled.png"
ren "Grid Insert Row-2.png" "Grid_Insert_Row_2_disabled.png"
ren "Grid Insert Row.png" "Grid_Insert_Row_disabled.png"
ren "Grid-2.png" "Grid_2_disabled.png"
ren "Grid-Auto Format-2.png" "Grid_Auto_Format_2_disabled.png"
ren "Grid-Auto Format.png" "Grid_Auto_Format_disabled.png"
ren "Grid-Column Width.png" "Grid_Column_Width_disabled.png"
ren "Grid-Delete Cell.png" "Grid_Delete_Cell_disabled.png"
ren "Grid-Delete Column.png" "Grid_Delete_Column_disabled.png"
ren "Grid-Delete Row.png" "Grid_Delete_Row_disabled.png"
ren "Grid-Delete-2.png" "Grid_Delete_2_disabled.png"
ren "Grid-Delete.png" "Grid_Delete_disabled.png"
ren "Grid-Insert Cell.png" "Grid_Insert_Cell_disabled.png"
ren "Grid-Insert Column Left.png" "Grid_Insert_Column_Left_disabled.png"
ren "Grid-Insert Column Right.png" "Grid_Insert_Column_Right_disabled.png"
ren "Grid-Insert Column.png" "Grid_Insert_Column_disabled.png"
ren "Grid-Insert Row Above.png" "Grid_Insert_Row_Above_disabled.png"
ren "Grid-Insert Row Below.png" "Grid_Insert_Row_Below_disabled.png"
ren "Grid-Insert Row.png" "Grid_Insert_Row_disabled.png"
ren "Grid-Merge Cells.png" "Grid_Merge_Cells_disabled.png"
ren "Grid-New-2.png" "Grid_New_2_disabled.png"
ren "Grid-New.png" "Grid_New_disabled.png"
ren "Grid-Options-2.png" "Grid_Options_2_disabled.png"
ren "Grid-Options.png" "Grid_Options_disabled.png"
ren "Grid-Row Height.png" "Grid_Row_Height_disabled.png"
ren "Grid-Select All-2.png" "Grid_Select_All_2_disabled.png"
ren "Grid-Select All.png" "Grid_Select_All_disabled.png"
ren "Grid-Select Cell-2.png" "Grid_Select_Cell_2_disabled.png"
ren "Grid-Select Cell.png" "Grid_Select_Cell_disabled.png"
ren "Grid-Select Column-2.png" "Grid_Select_Column_2_disabled.png"
ren "Grid-Select Column.png" "Grid_Select_Column_disabled.png"
ren "Grid-Select Row-2.png" "Grid_Select_Row_2_disabled.png"
ren "Grid-Select Row.png" "Grid_Select_Row_disabled.png"
ren "Grid-Split Cells-2.png" "Grid_Split_Cells_2_disabled.png"
ren "Grid-Split Cells.png" "Grid_Split_Cells_disabled.png"
ren "Grid-Wizard-2.png" "Grid_Wizard_2_disabled.png"
ren "Grid-Wizard.png" "Grid_Wizard_disabled.png"
ren "Grid.png" "Grid_disabled.png"
ren "Hand Held.png" "Hand_Held_disabled.png"
ren "Hand Shake.png" "Hand_Shake_disabled.png"
ren "Header and Footer-Toggle.png" "Header_and_Footer_Toggle_disabled.png"
ren "Header and Footer.png" "Header_and_Footer_disabled.png"
ren "Header-Next.png" "Header_Next_disabled.png"
ren "Header-Previous.png" "Header_Previous_disabled.png"
ren "Header.png" "Header_disabled.png"
ren "Help.png" "Help_disabled.png"
ren "Highlighter.png" "Highlighter_disabled.png"
ren "History.png" "History_disabled.png"
ren "Home.png" "Home_disabled.png"
ren "Image-Brightness.png" "Image_Brightness_disabled.png"
ren "Image-Colour.png" "Image_Colour_disabled.png"
ren "Image-Contrast.png" "Image_Contrast_disabled.png"
ren "Image-Crop.png" "Image_Crop_disabled.png"
ren "Image-Flip.png" "Image_Flip_disabled.png"
ren "Image-Mirror.png" "Image_Mirror_disabled.png"
ren "Image-Paint.png" "Image_Paint_disabled.png"
ren "Image-Resize.png" "Image_Resize_disabled.png"
ren "Image-Rotate.png" "Image_Rotate_disabled.png"
ren "Image-Select.png" "Image_Select_disabled.png"
ren "Image.png" "Image_disabled.png"
ren "Import-Access.png" "Import_Access_disabled.png"
ren "Import-Acrobat.png" "Import_Acrobat_disabled.png"
ren "Import-CSV.png" "Import_CSV_disabled.png"
ren "Import-Excel.png" "Import_Excel_disabled.png"
ren "Import-Fixed Length.png" "Import_Fixed_Length_disabled.png"
ren "Import-HTML.png" "Import_HTML_disabled.png"
ren "Import-Outlook.png" "Import_Outlook_disabled.png"
ren "Import-RTF.png" "Import_RTF_disabled.png"
ren "Import-Text.png" "Import_Text_disabled.png"
ren "Import-Word.png" "Import_Word_disabled.png"
ren "Import-XML.png" "Import_XML_disabled.png"
ren "Import.png" "Import_disabled.png"
ren "Indent-Decrease-2.png" "Indent_Decrease_2_disabled.png"
ren "Indent-Decrease.png" "Indent_Decrease_disabled.png"
ren "Indent-Increase-2.png" "Indent_Increase_2_disabled.png"
ren "Indent-Increase.png" "Indent_Increase_disabled.png"
ren "Insert-File.png" "Insert_File_disabled.png"
ren "Insert-Image.png" "Insert_Image_disabled.png"
ren "Insert-Object.png" "Insert_Object_disabled.png"
ren "Insert.png" "Insert_disabled.png"
ren "Invoice.png" "Invoice_disabled.png"
ren "Italic-2.png" "Italic_2_disabled.png"
ren "Italic.png" "Italic_disabled.png"
ren "Key.png" "Key_disabled.png"
ren "Landscape.png" "Landscape_disabled.png"
ren "Launch.png" "Launch_disabled.png"
ren "Letter.png" "Letter_disabled.png"
ren "Line Spacing-2.png" "Line_Spacing_2_disabled.png"
ren "Line Spacing.png" "Line_Spacing_disabled.png"
ren "Link.png" "Link_disabled.png"
ren "list.txt" "list_disabled.png"
ren "Lock.png" "Lock_disabled.png"
ren "Mail-Forward.png" "Mail_Forward_disabled.png"
ren "Mail-In Box-2.png" "Mail_In_Box_2_disabled.png"
ren "Mail-In Box.png" "Mail_In_Box_disabled.png"
ren "Mail-In-Out Box.png" "Mail_In_Out_Box_disabled.png"
ren "Mail-New.png" "Mail_New_disabled.png"
ren "Mail-Out Box-2.png" "Mail_Out_Box_2_disabled.png"
ren "Mail-Out Box.png" "Mail_Out_Box_disabled.png"
ren "Mail-Reply To All.png" "Mail_Reply_To_All_disabled.png"
ren "Mail-Reply.png" "Mail_Reply_disabled.png"
ren "Mail-Search.png" "Mail_Search_disabled.png"
ren "Mail-Send and Receive.png" "Mail_Send_and_Receive_disabled.png"
ren "Mail.png" "Mail_disabled.png"
ren "Media.png" "Media_disabled.png"
ren "Microphone.png" "Microphone_disabled.png"
ren "Midi Keyboard.png" "Midi_Keyboard_disabled.png"
ren "Minus.png" "Minus_disabled.png"
ren "mm-Eject.png" "mm_Eject_disabled.png"
ren "mm-Fast Forward.png" "mm_Fast_Forward_disabled.png"
ren "mm-First.png" "mm_First_disabled.png"
ren "mm-Last.png" "mm_Last_disabled.png"
ren "mm-Pause.png" "mm_Pause_disabled.png"
ren "mm-Play.png" "mm_Play_disabled.png"
ren "mm-Rewind.png" "mm_Rewind_disabled.png"
ren "mm-Stop.png" "mm_Stop_disabled.png"
ren "Monitor.png" "Monitor_disabled.png"
ren "Movie.png" "Movie_disabled.png"
ren "Musical Note-2.png" "Musical_Note_2_disabled.png"
ren "Musical Note.png" "Musical_Note_disabled.png"
ren "New.png" "New_disabled.png"
ren "Note-Add.png" "Note_Add_disabled.png"
ren "Note-Delete.png" "Note_Delete_disabled.png"
ren "Note-Edit.png" "Note_Edit_disabled.png"
ren "Note-New.png" "Note_New_disabled.png"
ren "Note-Next.png" "Note_Next_disabled.png"
ren "Note-Previous.png" "Note_Previous_disabled.png"
ren "Note-Remove.png" "Note_Remove_disabled.png"
ren "Note-Search.png" "Note_Search_disabled.png"
ren "Note.png" "Note_disabled.png"
ren "Notepad.png" "Notepad_disabled.png"
ren "Notes.png" "Notes_disabled.png"
ren "Number of Pages.png" "Number_of_Pages_disabled.png"
ren "Numbering-2.png" "Numbering_2_disabled.png"
ren "Numbering.png" "Numbering_disabled.png"
ren "Object-Bring To Front.png" "Object_Bring_To_Front_disabled.png"
ren "Object-Select.png" "Object_Select_disabled.png"
ren "Object-Send To Back.png" "Object_Send_To_Back_disabled.png"
ren "Open.png" "Open_disabled.png"
ren "Outline-2.png" "Outline_2_disabled.png"
ren "Outline.png" "Outline_disabled.png"
ren "Page Number.png" "Page_Number_disabled.png"
ren "Page-Break.png" "Page_Break_disabled.png"
ren "Page-Invert.png" "Page_Invert_disabled.png"
ren "Page-Next.png" "Page_Next_disabled.png"
ren "Page-Previous.png" "Page_Previous_disabled.png"
ren "Page-Setup.png" "Page_Setup_disabled.png"
ren "Paintbrush.png" "Paintbrush_disabled.png"
ren "Parcel.png" "Parcel_disabled.png"
ren "Paste.png" "Paste_disabled.png"
ren "Permission.png" "Permission_disabled.png"
ren "Phone.png" "Phone_disabled.png"
ren "Planner.png" "Planner_disabled.png"
ren "Plus.png" "Plus_disabled.png"
ren "Portrait.png" "Portrait_disabled.png"
ren "Preview.png" "Preview_disabled.png"
ren "Print-2.png" "Print_2_disabled.png"
ren "Print-Options-2.png" "Print_Options_2_disabled.png"
ren "Print-Options.png" "Print_Options_disabled.png"
ren "Print.png" "Print_disabled.png"
ren "Procedure.png" "Procedure_disabled.png"
ren "Process.png" "Process_disabled.png"
ren "Project-Gant Chart.png" "Project_Gant_Chart_disabled.png"
ren "Project.png" "Project_disabled.png"
ren "Properties.png" "Properties_disabled.png"
ren "Push Pin.png" "Push_Pin_disabled.png"
ren "Recycle Bin.png" "Recycle_Bin_disabled.png"
ren "Redo.png" "Redo_disabled.png"
ren "Refresh.png" "Refresh_disabled.png"
ren "Remove.png" "Remove_disabled.png"
ren "Rename.png" "Rename_disabled.png"
ren "Report-2.png" "Report_2_disabled.png"
ren "Report-Bound.png" "Report_Bound_disabled.png"
ren "Report.png" "Report_disabled.png"
ren "Research.png" "Research_disabled.png"
ren "Ruler-Formatting.png" "Ruler_Formatting_disabled.png"
ren "Ruler.png" "Ruler_disabled.png"
ren "Save All.png" "Save_All_disabled.png"
ren "Save As HTML.png" "Save_As_HTML_disabled.png"
ren "Save As.png" "Save_As_disabled.png"
ren "Save Draft.png" "Save_Draft_disabled.png"
ren "Save.png" "Save_disabled.png"
ren "Script.png" "Script_disabled.png"
ren "Search-Next.png" "Search_Next_disabled.png"
ren "Search-Previous.png" "Search_Previous_disabled.png"
ren "Search-Replace.png" "Search_Replace_disabled.png"
ren "Search.png" "Search_disabled.png"
ren "Select All-2.png" "Select_All_2_disabled.png"
ren "Select All.png" "Select_All_disabled.png"
ren "Selection-None.png" "Selection_None_disabled.png"
ren "Slide Show.png" "Slide_Show_disabled.png"
ren "Slide.png" "Slide_disabled.png"
ren "Software-Analyse.png" "Software_Analyse_disabled.png"
ren "Sort Ascending.png" "Sort_Ascending_disabled.png"
ren "Sort Descending.png" "Sort_Descending_disabled.png"
ren "Sort-Ascending.png" "Sort_Ascending_disabled.png"
ren "Sort-Descending.png" "Sort_Descending_disabled.png"
ren "Sound-Delete.png" "Sound_Delete_disabled.png"
ren "Sound-Fade In.png" "Sound_Fade_In_disabled.png"
ren "Sound-Fade Out.png" "Sound_Fade_Out_disabled.png"
ren "Sound-Join.png" "Sound_Join_disabled.png"
ren "Sound-Mark End.png" "Sound_Mark_End_disabled.png"
ren "Sound-Mark Start.png" "Sound_Mark_Start_disabled.png"
ren "Sound-Split.png" "Sound_Split_disabled.png"
ren "Spell Check.png" "Spell_Check_disabled.png"
ren "Stop.png" "Stop_disabled.png"
ren "Strikeout-2.png" "Strikeout_2_disabled.png"
ren "Strikeout.png" "Strikeout_disabled.png"
ren "Subscript-2.png" "Subscript_2_disabled.png"
ren "Subscript.png" "Subscript_disabled.png"
ren "Sum-2.png" "Sum_2_disabled.png"
ren "Sum.png" "Sum_disabled.png"
ren "Summary.png" "Summary_disabled.png"
ren "Superscript-2.png" "Superscript_2_disabled.png"
ren "Superscript.png" "Superscript_disabled.png"
ren "Support.png" "Support_disabled.png"
ren "Tables and Borders.png" "Tables_and_Borders_disabled.png"
ren "Task-Search.png" "Task_Search_disabled.png"
ren "Task.png" "Task_disabled.png"
ren "Thesaurus.png" "Thesaurus_disabled.png"
ren "Tick.png" "Tick_disabled.png"
ren "Time Line.png" "Time_Line_disabled.png"
ren "Tip.png" "Tip_disabled.png"
ren "To Do List.png" "To_Do_List_disabled.png"
ren "To Lowercase.png" "To_Lowercase_disabled.png"
ren "To Uppercase.png" "To_Uppercase_disabled.png"
ren "Tools.png" "Tools_disabled.png"
ren "Tree View-Add.png" "Tree_View_Add_disabled.png"
ren "Tree View-Delete.png" "Tree_View_Delete_disabled.png"
ren "Tree View-Edit.png" "Tree_View_Edit_disabled.png"
ren "Tree View-New.png" "Tree_View_New_disabled.png"
ren "Tree View-Remove.png" "Tree_View_Remove_disabled.png"
ren "Tree View-Search.png" "Tree_View_Search_disabled.png"
ren "Tree View.png" "Tree_View_disabled.png"
ren "Underline-2.png" "Underline_2_disabled.png"
ren "Underline.png" "Underline_disabled.png"
ren "Undo.png" "Undo_disabled.png"
ren "Unlock.png" "Unlock_disabled.png"
ren "User-2.png" "User_2_disabled.png"
ren "User-Add-2.png" "User_Add_2_disabled.png"
ren "User-Add.png" "User_Add_disabled.png"
ren "User-Delete-2.png" "User_Delete_2_disabled.png"
ren "User-Delete.png" "User_Delete_disabled.png"
ren "User-Edit-2.png" "User_Edit_2_disabled.png"
ren "User-Edit.png" "User_Edit_disabled.png"
ren "User-New-2.png" "User_New_2_disabled.png"
ren "User-New.png" "User_New_disabled.png"
ren "User-Options-2.png" "User_Options_2_disabled.png"
ren "User-Options.png" "User_Options_disabled.png"
ren "User-Password-2.png" "User_Password_2_disabled.png"
ren "User-Password.png" "User_Password_disabled.png"
ren "User-Remove-2.png" "User_Remove_2_disabled.png"
ren "User-Remove.png" "User_Remove_disabled.png"
ren "User-Search-2.png" "User_Search_2_disabled.png"
ren "User-Search.png" "User_Search_disabled.png"
ren "User-Security-2.png" "User_Security_2_disabled.png"
ren "User-Security.png" "User_Security_disabled.png"
ren "User.png" "User_disabled.png"
ren "Users-2.png" "Users_2_disabled.png"
ren "Users.png" "Users_disabled.png"
ren "View-Details.png" "View_Details_disabled.png"
ren "View-Large Icons.png" "View_Large_Icons_disabled.png"
ren "View-List.png" "View_List_disabled.png"
ren "View-One Page.png" "View_One_Page_disabled.png"
ren "View-Page Width.png" "View_Page_Width_disabled.png"
ren "View-Small Icons.png" "View_Small_Icons_disabled.png"
ren "Views.png" "Views_disabled.png"
ren "Volume-Mute.png" "Volume_Mute_disabled.png"
ren "Volume.png" "Volume_disabled.png"
ren "Warning.png" "Warning_disabled.png"
ren "Waste Bin.png" "Waste_Bin_disabled.png"
ren "Window-Add.png" "Window_Add_disabled.png"
ren "Window-Bring To Front.png" "Window_Bring_To_Front_disabled.png"
ren "Window-Cascade.png" "Window_Cascade_disabled.png"
ren "Window-Close.png" "Window_Close_disabled.png"
ren "Window-Delete.png" "Window_Delete_disabled.png"
ren "Window-Edit.png" "Window_Edit_disabled.png"
ren "Window-Maximise.png" "Window_Maximise_disabled.png"
ren "Window-Minimise.png" "Window_Minimise_disabled.png"
ren "Window-New.png" "Window_New_disabled.png"
ren "Window-Next.png" "Window_Next_disabled.png"
ren "Window-Options.png" "Window_Options_disabled.png"
ren "Window-Preview.png" "Window_Preview_disabled.png"
ren "Window-Previous.png" "Window_Previous_disabled.png"
ren "Window-Properties.png" "Window_Properties_disabled.png"
ren "Window-Remove.png" "Window_Remove_disabled.png"
ren "Window-Search.png" "Window_Search_disabled.png"
ren "Window-Send To Back.png" "Window_Send_To_Back_disabled.png"
ren "Window-Split.png" "Window_Split_disabled.png"
ren "Window-Tile Horizontal.png" "Window_Tile_Horizontal_disabled.png"
ren "Window-Tile Vertical.png" "Window_Tile_Vertical_disabled.png"
ren "Window.png" "Window_disabled.png"
ren "Wizard.png" "Wizard_disabled.png"
ren "Word Count.png" "Word_Count_disabled.png"
ren "Word Wrap-2.png" "Word_Wrap_2_disabled.png"
ren "Word Wrap.png" "Word_Wrap_disabled.png"
ren "Work Sheet-Auto Format.png" "Work_Sheet_Auto_Format_disabled.png"
ren "Work Sheet-Delete.png" "Work_Sheet_Delete_disabled.png"
ren "Work Sheet-New.png" "Work_Sheet_New_disabled.png"
ren "Work Sheet-Options.png" "Work_Sheet_Options_disabled.png"
ren "Work Sheet-Protect.png" "Work_Sheet_Protect_disabled.png"
ren "Work Sheet-Rename.png" "Work_Sheet_Rename_disabled.png"
ren "Work Sheet.png" "Work_Sheet_disabled.png"
ren "Zoom-In.png" "Zoom_In_disabled.png"
ren "Zoom-Out.png" "Zoom_Out_disabled.png"
