ren "About.png" "About_hot.png"
ren "Accounts.png" "Accounts_hot.png"
ren "Address Book.png" "Address_Book_hot.png"
ren "Air Brush.png" "Air_Brush_hot.png"
ren "Align-Centre-2.png" "Align_Centre_2_hot.png"
ren "Align-Centre.png" "Align_Centre_hot.png"
ren "Align-Full-2.png" "Align_Full_2_hot.png"
ren "Align-Full.png" "Align_Full_hot.png"
ren "Align-Justify.png" "Align_Justify_hot.png"
ren "Align-Left-2.png" "Align_Left_2_hot.png"
ren "Align-Left.png" "Align_Left_hot.png"
ren "Align-Right-2.png" "Align_Right_2_hot.png"
ren "Align-Right.png" "Align_Right_hot.png"
ren "Arrow-Left Right.png" "Arrow_Left_Right_hot.png"
ren "Arrow-Up Down.png" "Arrow_Up_Down_hot.png"
ren "Attachment.png" "Attachment_hot.png"
ren "Auto Correct-Options.png" "Auto_Correct_Options_hot.png"
ren "Auto-Type.png" "Auto_Type_hot.png"
ren "Back.png" "Back_hot.png"
ren "Bar Code.png" "Bar_Code_hot.png"
ren "Bold-2.png" "Bold_2_hot.png"
ren "Bold.png" "Bold_hot.png"
ren "Book-Open.png" "Book_Open_hot.png"
ren "Book-Search.png" "Book_Search_hot.png"
ren "Books.png" "Books_hot.png"
ren "Borders and Shading.png" "Borders_and_Shading_hot.png"
ren "Box-Closed-2.png" "Box_Closed_2_hot.png"
ren "Box-Closed.png" "Box_Closed_hot.png"
ren "Box-Open-2.png" "Box_Open_2_hot.png"
ren "Box-Open.png" "Box_Open_hot.png"
ren "Bullets-2.png" "Bullets_2_hot.png"
ren "Bullets.png" "Bullets_hot.png"
ren "Calculator.png" "Calculator_hot.png"
ren "Calendar-Go To Date.png" "Calendar_Go_To_Date_hot.png"
ren "Calendar-Search.png" "Calendar_Search_hot.png"
ren "Calendar-Select Day.png" "Calendar_Select_Day_hot.png"
ren "Calendar-Select Month.png" "Calendar_Select_Month_hot.png"
ren "Calendar-Select Week.png" "Calendar_Select_Week_hot.png"
ren "Calendar-Select Work Week.png" "Calendar_Select_Work_Week_hot.png"
ren "Calendar.png" "Calendar_hot.png"
ren "Camera-Photo.png" "Camera_Photo_hot.png"
ren "Camera.png" "Camera_hot.png"
ren "Card File.png" "Card_File_hot.png"
ren "Card-Add.png" "Card_Add_hot.png"
ren "Card-Delete.png" "Card_Delete_hot.png"
ren "Card-Edit.png" "Card_Edit_hot.png"
ren "Card-New.png" "Card_New_hot.png"
ren "Card-Next.png" "Card_Next_hot.png"
ren "Card-Previous.png" "Card_Previous_hot.png"
ren "Card-Remove.png" "Card_Remove_hot.png"
ren "Card-Search.png" "Card_Search_hot.png"
ren "Card.png" "Card_hot.png"
ren "CD-Burn.png" "CD_Burn_hot.png"
ren "CD-In Case.png" "CD_In_Case_hot.png"
ren "CD-Rom.png" "CD_Rom_hot.png"
ren "Center Across Cells.png" "Center_Across_Cells_hot.png"
ren "Certificate.png" "Certificate_hot.png"
ren "Chart-Bar.png" "Chart_Bar_hot.png"
ren "Chart-Line.png" "Chart_Line_hot.png"
ren "Chart-Pie.png" "Chart_Pie_hot.png"
ren "Chart-Point.png" "Chart_Point_hot.png"
ren "Chart.png" "Chart_hot.png"
ren "Clean.png" "Clean_hot.png"
ren "Clear.png" "Clear_hot.png"
ren "Clipboard.png" "Clipboard_hot.png"
ren "Clock.png" "Clock_hot.png"
ren "Close.png" "Close_hot.png"
ren "Colour Picker.png" "Colour_Picker_hot.png"
ren "Columns-2.png" "Columns_2_hot.png"
ren "Columns.png" "Columns_hot.png"
ren "Command Prompt.png" "Command_Prompt_hot.png"
ren "Compress.png" "Compress_hot.png"
ren "Computer.png" "Computer_hot.png"
ren "Connect.png" "Connect_hot.png"
ren "Contact-Add.png" "Contact_Add_hot.png"
ren "Contact-Delete.png" "Contact_Delete_hot.png"
ren "Contact-Edit.png" "Contact_Edit_hot.png"
ren "Contact-New.png" "Contact_New_hot.png"
ren "Contact-Remove.png" "Contact_Remove_hot.png"
ren "Contact-Search.png" "Contact_Search_hot.png"
ren "Contact.png" "Contact_hot.png"
ren "Copy.png" "Copy_hot.png"
ren "Cross.png" "Cross_hot.png"
ren "Currency-Notes.png" "Currency_Notes_hot.png"
ren "Currency.png" "Currency_hot.png"
ren "Cut.png" "Cut_hot.png"
ren "Database-Add.png" "Database_Add_hot.png"
ren "Database-Close.png" "Database_Close_hot.png"
ren "Database-Delete.png" "Database_Delete_hot.png"
ren "Database-Edit.png" "Database_Edit_hot.png"
ren "Database-Filter.png" "Database_Filter_hot.png"
ren "Database-New.png" "Database_New_hot.png"
ren "Database-Open.png" "Database_Open_hot.png"
ren "Database-Options.png" "Database_Options_hot.png"
ren "Database-Properties.png" "Database_Properties_hot.png"
ren "Database-Remove.png" "Database_Remove_hot.png"
ren "Database-Save.png" "Database_Save_hot.png"
ren "Database-Schema.png" "Database_Schema_hot.png"
ren "Database-Search.png" "Database_Search_hot.png"
ren "Database-Security.png" "Database_Security_hot.png"
ren "Database-Wizard.png" "Database_Wizard_hot.png"
ren "Database.png" "Database_hot.png"
ren "Date-Time.png" "Date_Time_hot.png"
ren "db-Add.png" "db_Add_hot.png"
ren "db-Cancel.png" "db_Cancel_hot.png"
ren "db-Delete.png" "db_Delete_hot.png"
ren "db-Edit.png" "db_Edit_hot.png"
ren "db-First.png" "db_First_hot.png"
ren "db-Last.png" "db_Last_hot.png"
ren "db-Next.png" "db_Next_hot.png"
ren "db-Post.png" "db_Post_hot.png"
ren "db-Previous.png" "db_Previous_hot.png"
ren "db-Refresh.png" "db_Refresh_hot.png"
ren "Decimals-Decrease.png" "Decimals_Decrease_hot.png"
ren "Decimals-Increase-2.png" "Decimals_Increase_2_hot.png"
ren "Decimals-Increase.png" "Decimals_Increase_hot.png"
ren "Decompress.png" "Decompress_hot.png"
ren "Delete-Blue.png" "Delete_Blue_hot.png"
ren "Delete.png" "Delete_hot.png"
ren "Design.png" "Design_hot.png"
ren "Desktop.png" "Desktop_hot.png"
ren "Dictionary.png" "Dictionary_hot.png"
ren "Disconnect.png" "Disconnect_hot.png"
ren "Discuss.png" "Discuss_hot.png"
ren "Doc-Access.png" "Doc_Access_hot.png"
ren "Doc-Acrobat.png" "Doc_Acrobat_hot.png"
ren "Doc-Excel.png" "Doc_Excel_hot.png"
ren "Doc-HTML.png" "Doc_HTML_hot.png"
ren "Doc-Outlook.png" "Doc_Outlook_hot.png"
ren "Doc-RTF.png" "Doc_RTF_hot.png"
ren "Doc-Word.png" "Doc_Word_hot.png"
ren "Doc-XML.png" "Doc_XML_hot.png"
ren "Document-Auto Format.png" "Document_Auto_Format_hot.png"
ren "Document-Protect.png" "Document_Protect_hot.png"
ren "Drawing.png" "Drawing_hot.png"
ren "Edit.png" "Edit_hot.png"
ren "Equaliser.png" "Equaliser_hot.png"
ren "Execute.png" "Execute_hot.png"
ren "Exit.png" "Exit_hot.png"
ren "Export-Access.png" "Export_Access_hot.png"
ren "Export-Acrobat.png" "Export_Acrobat_hot.png"
ren "Export-CSV.png" "Export_CSV_hot.png"
ren "Export-Excel.png" "Export_Excel_hot.png"
ren "Export-Fixed Length.png" "Export_Fixed_Length_hot.png"
ren "Export-HTML.png" "Export_HTML_hot.png"
ren "Export-Outlook.png" "Export_Outlook_hot.png"
ren "Export-RTF.png" "Export_RTF_hot.png"
ren "Export-Text.png" "Export_Text_hot.png"
ren "Export-Word.png" "Export_Word_hot.png"
ren "Export-XML.png" "Export_XML_hot.png"
ren "Export.png" "Export_hot.png"
ren "Favorites.png" "Favorites_hot.png"
ren "Fill-Down.png" "Fill_Down_hot.png"
ren "Fill-Left.png" "Fill_Left_hot.png"
ren "Fill-Right.png" "Fill_Right_hot.png"
ren "Fill-Up.png" "Fill_Up_hot.png"
ren "Fill.png" "Fill_hot.png"
ren "Filter.png" "Filter_hot.png"
ren "Flag-Delete.png" "Flag_Delete_hot.png"
ren "Flag-Next.png" "Flag_Next_hot.png"
ren "Flag-Previous.png" "Flag_Previous_hot.png"
ren "Flag.png" "Flag_hot.png"
ren "Flow Chart.png" "Flow_Chart_hot.png"
ren "Folder List.png" "Folder_List_hot.png"
ren "Folder-Closed.png" "Folder_Closed_hot.png"
ren "Folder-Delete.png" "Folder_Delete_hot.png"
ren "Folder-New.png" "Folder_New_hot.png"
ren "Folder-Options.png" "Folder_Options_hot.png"
ren "Folder-Search.png" "Folder_Search_hot.png"
ren "Folder.png" "Folder_hot.png"
ren "Footer.png" "Footer_hot.png"
ren "Format Font.png" "Format_Font_hot.png"
ren "Format Painter.png" "Format_Painter_hot.png"
ren "Format-Font Size.png" "Format_Font_Size_hot.png"
ren "Format-Font.png" "Format_Font_hot.png"
ren "Format-Paragraph-2.png" "Format_Paragraph_2_hot.png"
ren "Format-Paragraph.png" "Format_Paragraph_hot.png"
ren "Format-Percentage-2.png" "Format_Percentage_2_hot.png"
ren "Format-Percentage.png" "Format_Percentage_hot.png"
ren "Formatting-Remove.png" "Formatting_Remove_hot.png"
ren "Forward.png" "Forward_hot.png"
ren "Full Screen-New.png" "Full_Screen_New_hot.png"
ren "Full Screen.png" "Full_Screen_hot.png"
ren "Function-2.png" "Function_2_hot.png"
ren "Function.png" "Function_hot.png"
ren "Go To Line.png" "Go_To_Line_hot.png"
ren "Grid Delete Column.png" "Grid_Delete_Column_hot.png"
ren "Grid Delete Row-2.png" "Grid_Delete_Row_2_hot.png"
ren "Grid Delete Row.png" "Grid_Delete_Row_hot.png"
ren "Grid Insert Column To Left.png" "Grid_Insert_Column_To_Left_hot.png"
ren "Grid Insert Column To Right.png" "Grid_Insert_Column_To_Right_hot.png"
ren "Grid Insert Column.png" "Grid_Insert_Column_hot.png"
ren "Grid Insert Row Above-2.png" "Grid_Insert_Row_Above_2_hot.png"
ren "Grid Insert Row Above.png" "Grid_Insert_Row_Above_hot.png"
ren "Grid Insert Row Below-2.png" "Grid_Insert_Row_Below_2_hot.png"
ren "Grid Insert Row Below.png" "Grid_Insert_Row_Below_hot.png"
ren "Grid Insert Row-2.png" "Grid_Insert_Row_2_hot.png"
ren "Grid Insert Row.png" "Grid_Insert_Row_hot.png"
ren "Grid-2.png" "Grid_2_hot.png"
ren "Grid-Auto Format-2.png" "Grid_Auto_Format_2_hot.png"
ren "Grid-Auto Format.png" "Grid_Auto_Format_hot.png"
ren "Grid-Column Width.png" "Grid_Column_Width_hot.png"
ren "Grid-Delete Cell.png" "Grid_Delete_Cell_hot.png"
ren "Grid-Delete Column.png" "Grid_Delete_Column_hot.png"
ren "Grid-Delete Row.png" "Grid_Delete_Row_hot.png"
ren "Grid-Delete-2.png" "Grid_Delete_2_hot.png"
ren "Grid-Delete.png" "Grid_Delete_hot.png"
ren "Grid-Insert Cell.png" "Grid_Insert_Cell_hot.png"
ren "Grid-Insert Column Left.png" "Grid_Insert_Column_Left_hot.png"
ren "Grid-Insert Column Right.png" "Grid_Insert_Column_Right_hot.png"
ren "Grid-Insert Column.png" "Grid_Insert_Column_hot.png"
ren "Grid-Insert Row Above.png" "Grid_Insert_Row_Above_hot.png"
ren "Grid-Insert Row Below.png" "Grid_Insert_Row_Below_hot.png"
ren "Grid-Insert Row.png" "Grid_Insert_Row_hot.png"
ren "Grid-Merge Cells.png" "Grid_Merge_Cells_hot.png"
ren "Grid-New-2.png" "Grid_New_2_hot.png"
ren "Grid-New.png" "Grid_New_hot.png"
ren "Grid-Options-2.png" "Grid_Options_2_hot.png"
ren "Grid-Options.png" "Grid_Options_hot.png"
ren "Grid-Row Height.png" "Grid_Row_Height_hot.png"
ren "Grid-Select All-2.png" "Grid_Select_All_2_hot.png"
ren "Grid-Select All.png" "Grid_Select_All_hot.png"
ren "Grid-Select Cell-2.png" "Grid_Select_Cell_2_hot.png"
ren "Grid-Select Cell.png" "Grid_Select_Cell_hot.png"
ren "Grid-Select Column-2.png" "Grid_Select_Column_2_hot.png"
ren "Grid-Select Column.png" "Grid_Select_Column_hot.png"
ren "Grid-Select Row-2.png" "Grid_Select_Row_2_hot.png"
ren "Grid-Select Row.png" "Grid_Select_Row_hot.png"
ren "Grid-Split Cells-2.png" "Grid_Split_Cells_2_hot.png"
ren "Grid-Split Cells.png" "Grid_Split_Cells_hot.png"
ren "Grid-Wizard-2.png" "Grid_Wizard_2_hot.png"
ren "Grid-Wizard.png" "Grid_Wizard_hot.png"
ren "Grid.png" "Grid_hot.png"
ren "Hand Held.png" "Hand_Held_hot.png"
ren "Hand Shake.png" "Hand_Shake_hot.png"
ren "Header and Footer-Toggle.png" "Header_and_Footer_Toggle_hot.png"
ren "Header and Footer.png" "Header_and_Footer_hot.png"
ren "Header-Next.png" "Header_Next_hot.png"
ren "Header-Previous.png" "Header_Previous_hot.png"
ren "Header.png" "Header_hot.png"
ren "Help.png" "Help_hot.png"
ren "Highlighter.png" "Highlighter_hot.png"
ren "History.png" "History_hot.png"
ren "Home.png" "Home_hot.png"
ren "Image-Brightness.png" "Image_Brightness_hot.png"
ren "Image-Colour.png" "Image_Colour_hot.png"
ren "Image-Contrast.png" "Image_Contrast_hot.png"
ren "Image-Crop.png" "Image_Crop_hot.png"
ren "Image-Flip.png" "Image_Flip_hot.png"
ren "Image-Mirror.png" "Image_Mirror_hot.png"
ren "Image-Paint.png" "Image_Paint_hot.png"
ren "Image-Resize.png" "Image_Resize_hot.png"
ren "Image-Rotate.png" "Image_Rotate_hot.png"
ren "Image-Select.png" "Image_Select_hot.png"
ren "Image.png" "Image_hot.png"
ren "Import-Access.png" "Import_Access_hot.png"
ren "Import-Acrobat.png" "Import_Acrobat_hot.png"
ren "Import-CSV.png" "Import_CSV_hot.png"
ren "Import-Excel.png" "Import_Excel_hot.png"
ren "Import-Fixed Length.png" "Import_Fixed_Length_hot.png"
ren "Import-HTML.png" "Import_HTML_hot.png"
ren "Import-Outlook.png" "Import_Outlook_hot.png"
ren "Import-RTF.png" "Import_RTF_hot.png"
ren "Import-Text.png" "Import_Text_hot.png"
ren "Import-Word.png" "Import_Word_hot.png"
ren "Import-XML.png" "Import_XML_hot.png"
ren "Import.png" "Import_hot.png"
ren "Indent-Decrease-2.png" "Indent_Decrease_2_hot.png"
ren "Indent-Decrease.png" "Indent_Decrease_hot.png"
ren "Indent-Increase-2.png" "Indent_Increase_2_hot.png"
ren "Indent-Increase.png" "Indent_Increase_hot.png"
ren "Insert-File.png" "Insert_File_hot.png"
ren "Insert-Image.png" "Insert_Image_hot.png"
ren "Insert-Object.png" "Insert_Object_hot.png"
ren "Insert.png" "Insert_hot.png"
ren "Invoice.png" "Invoice_hot.png"
ren "Italic-2.png" "Italic_2_hot.png"
ren "Italic.png" "Italic_hot.png"
ren "Key.png" "Key_hot.png"
ren "Landscape.png" "Landscape_hot.png"
ren "Launch.png" "Launch_hot.png"
ren "Letter.png" "Letter_hot.png"
ren "Line Spacing-2.png" "Line_Spacing_2_hot.png"
ren "Line Spacing.png" "Line_Spacing_hot.png"
ren "Link.png" "Link_hot.png"
ren "list.txt" "list_hot.png"
ren "Lock.png" "Lock_hot.png"
ren "Mail-Forward.png" "Mail_Forward_hot.png"
ren "Mail-In Box-2.png" "Mail_In_Box_2_hot.png"
ren "Mail-In Box.png" "Mail_In_Box_hot.png"
ren "Mail-In-Out Box.png" "Mail_In_Out_Box_hot.png"
ren "Mail-New.png" "Mail_New_hot.png"
ren "Mail-Out Box-2.png" "Mail_Out_Box_2_hot.png"
ren "Mail-Out Box.png" "Mail_Out_Box_hot.png"
ren "Mail-Reply To All.png" "Mail_Reply_To_All_hot.png"
ren "Mail-Reply.png" "Mail_Reply_hot.png"
ren "Mail-Search.png" "Mail_Search_hot.png"
ren "Mail-Send and Receive.png" "Mail_Send_and_Receive_hot.png"
ren "Mail.png" "Mail_hot.png"
ren "Media.png" "Media_hot.png"
ren "Microphone.png" "Microphone_hot.png"
ren "Midi Keyboard.png" "Midi_Keyboard_hot.png"
ren "Minus.png" "Minus_hot.png"
ren "mm-Eject.png" "mm_Eject_hot.png"
ren "mm-Fast Forward.png" "mm_Fast_Forward_hot.png"
ren "mm-First.png" "mm_First_hot.png"
ren "mm-Last.png" "mm_Last_hot.png"
ren "mm-Pause.png" "mm_Pause_hot.png"
ren "mm-Play.png" "mm_Play_hot.png"
ren "mm-Rewind.png" "mm_Rewind_hot.png"
ren "mm-Stop.png" "mm_Stop_hot.png"
ren "Monitor.png" "Monitor_hot.png"
ren "Movie.png" "Movie_hot.png"
ren "Musical Note-2.png" "Musical_Note_2_hot.png"
ren "Musical Note.png" "Musical_Note_hot.png"
ren "New.png" "New_hot.png"
ren "Note-Add.png" "Note_Add_hot.png"
ren "Note-Delete.png" "Note_Delete_hot.png"
ren "Note-Edit.png" "Note_Edit_hot.png"
ren "Note-New.png" "Note_New_hot.png"
ren "Note-Next.png" "Note_Next_hot.png"
ren "Note-Previous.png" "Note_Previous_hot.png"
ren "Note-Remove.png" "Note_Remove_hot.png"
ren "Note-Search.png" "Note_Search_hot.png"
ren "Note.png" "Note_hot.png"
ren "Notepad.png" "Notepad_hot.png"
ren "Notes.png" "Notes_hot.png"
ren "Number of Pages.png" "Number_of_Pages_hot.png"
ren "Numbering-2.png" "Numbering_2_hot.png"
ren "Numbering.png" "Numbering_hot.png"
ren "Object-Bring To Front.png" "Object_Bring_To_Front_hot.png"
ren "Object-Select.png" "Object_Select_hot.png"
ren "Object-Send To Back.png" "Object_Send_To_Back_hot.png"
ren "Open.png" "Open_hot.png"
ren "Outline-2.png" "Outline_2_hot.png"
ren "Outline.png" "Outline_hot.png"
ren "Page Number.png" "Page_Number_hot.png"
ren "Page-Break.png" "Page_Break_hot.png"
ren "Page-Invert.png" "Page_Invert_hot.png"
ren "Page-Next.png" "Page_Next_hot.png"
ren "Page-Previous.png" "Page_Previous_hot.png"
ren "Page-Setup.png" "Page_Setup_hot.png"
ren "Paintbrush.png" "Paintbrush_hot.png"
ren "Parcel.png" "Parcel_hot.png"
ren "Paste.png" "Paste_hot.png"
ren "Permission.png" "Permission_hot.png"
ren "Phone.png" "Phone_hot.png"
ren "Planner.png" "Planner_hot.png"
ren "Plus.png" "Plus_hot.png"
ren "Portrait.png" "Portrait_hot.png"
ren "Preview.png" "Preview_hot.png"
ren "Print-2.png" "Print_2_hot.png"
ren "Print-Options-2.png" "Print_Options_2_hot.png"
ren "Print-Options.png" "Print_Options_hot.png"
ren "Print.png" "Print_hot.png"
ren "Procedure.png" "Procedure_hot.png"
ren "Process.png" "Process_hot.png"
ren "Project-Gant Chart.png" "Project_Gant_Chart_hot.png"
ren "Project.png" "Project_hot.png"
ren "Properties.png" "Properties_hot.png"
ren "Push Pin.png" "Push_Pin_hot.png"
ren "Recycle Bin.png" "Recycle_Bin_hot.png"
ren "Redo.png" "Redo_hot.png"
ren "Refresh.png" "Refresh_hot.png"
ren "Remove.png" "Remove_hot.png"
ren "Rename.png" "Rename_hot.png"
ren "Report-2.png" "Report_2_hot.png"
ren "Report-Bound.png" "Report_Bound_hot.png"
ren "Report.png" "Report_hot.png"
ren "Research.png" "Research_hot.png"
ren "Ruler-Formatting.png" "Ruler_Formatting_hot.png"
ren "Ruler.png" "Ruler_hot.png"
ren "Save All.png" "Save_All_hot.png"
ren "Save As HTML.png" "Save_As_HTML_hot.png"
ren "Save As.png" "Save_As_hot.png"
ren "Save Draft.png" "Save_Draft_hot.png"
ren "Save.png" "Save_hot.png"
ren "Script.png" "Script_hot.png"
ren "Search-Next.png" "Search_Next_hot.png"
ren "Search-Previous.png" "Search_Previous_hot.png"
ren "Search-Replace.png" "Search_Replace_hot.png"
ren "Search.png" "Search_hot.png"
ren "Select All-2.png" "Select_All_2_hot.png"
ren "Select All.png" "Select_All_hot.png"
ren "Selection-None.png" "Selection_None_hot.png"
ren "Slide Show.png" "Slide_Show_hot.png"
ren "Slide.png" "Slide_hot.png"
ren "Software-Analyse.png" "Software_Analyse_hot.png"
ren "Sort Ascending.png" "Sort_Ascending_hot.png"
ren "Sort Descending.png" "Sort_Descending_hot.png"
ren "Sort-Ascending.png" "Sort_Ascending_hot.png"
ren "Sort-Descending.png" "Sort_Descending_hot.png"
ren "Sound-Delete.png" "Sound_Delete_hot.png"
ren "Sound-Fade In.png" "Sound_Fade_In_hot.png"
ren "Sound-Fade Out.png" "Sound_Fade_Out_hot.png"
ren "Sound-Join.png" "Sound_Join_hot.png"
ren "Sound-Mark End.png" "Sound_Mark_End_hot.png"
ren "Sound-Mark Start.png" "Sound_Mark_Start_hot.png"
ren "Sound-Split.png" "Sound_Split_hot.png"
ren "Spell Check.png" "Spell_Check_hot.png"
ren "Stop.png" "Stop_hot.png"
ren "Strikeout-2.png" "Strikeout_2_hot.png"
ren "Strikeout.png" "Strikeout_hot.png"
ren "Subscript-2.png" "Subscript_2_hot.png"
ren "Subscript.png" "Subscript_hot.png"
ren "Sum-2.png" "Sum_2_hot.png"
ren "Sum.png" "Sum_hot.png"
ren "Summary.png" "Summary_hot.png"
ren "Superscript-2.png" "Superscript_2_hot.png"
ren "Superscript.png" "Superscript_hot.png"
ren "Support.png" "Support_hot.png"
ren "Tables and Borders.png" "Tables_and_Borders_hot.png"
ren "Task-Search.png" "Task_Search_hot.png"
ren "Task.png" "Task_hot.png"
ren "Thesaurus.png" "Thesaurus_hot.png"
ren "Tick.png" "Tick_hot.png"
ren "Time Line.png" "Time_Line_hot.png"
ren "Tip.png" "Tip_hot.png"
ren "To Do List.png" "To_Do_List_hot.png"
ren "To Lowercase.png" "To_Lowercase_hot.png"
ren "To Uppercase.png" "To_Uppercase_hot.png"
ren "Tools.png" "Tools_hot.png"
ren "Tree View-Add.png" "Tree_View_Add_hot.png"
ren "Tree View-Delete.png" "Tree_View_Delete_hot.png"
ren "Tree View-Edit.png" "Tree_View_Edit_hot.png"
ren "Tree View-New.png" "Tree_View_New_hot.png"
ren "Tree View-Remove.png" "Tree_View_Remove_hot.png"
ren "Tree View-Search.png" "Tree_View_Search_hot.png"
ren "Tree View.png" "Tree_View_hot.png"
ren "Underline-2.png" "Underline_2_hot.png"
ren "Underline.png" "Underline_hot.png"
ren "Undo.png" "Undo_hot.png"
ren "Unlock.png" "Unlock_hot.png"
ren "User-2.png" "User_2_hot.png"
ren "User-Add-2.png" "User_Add_2_hot.png"
ren "User-Add.png" "User_Add_hot.png"
ren "User-Delete-2.png" "User_Delete_2_hot.png"
ren "User-Delete.png" "User_Delete_hot.png"
ren "User-Edit-2.png" "User_Edit_2_hot.png"
ren "User-Edit.png" "User_Edit_hot.png"
ren "User-New-2.png" "User_New_2_hot.png"
ren "User-New.png" "User_New_hot.png"
ren "User-Options-2.png" "User_Options_2_hot.png"
ren "User-Options.png" "User_Options_hot.png"
ren "User-Password-2.png" "User_Password_2_hot.png"
ren "User-Password.png" "User_Password_hot.png"
ren "User-Remove-2.png" "User_Remove_2_hot.png"
ren "User-Remove.png" "User_Remove_hot.png"
ren "User-Search-2.png" "User_Search_2_hot.png"
ren "User-Search.png" "User_Search_hot.png"
ren "User-Security-2.png" "User_Security_2_hot.png"
ren "User-Security.png" "User_Security_hot.png"
ren "User.png" "User_hot.png"
ren "Users-2.png" "Users_2_hot.png"
ren "Users.png" "Users_hot.png"
ren "View-Details.png" "View_Details_hot.png"
ren "View-Large Icons.png" "View_Large_Icons_hot.png"
ren "View-List.png" "View_List_hot.png"
ren "View-One Page.png" "View_One_Page_hot.png"
ren "View-Page Width.png" "View_Page_Width_hot.png"
ren "View-Small Icons.png" "View_Small_Icons_hot.png"
ren "Views.png" "Views_hot.png"
ren "Volume-Mute.png" "Volume_Mute_hot.png"
ren "Volume.png" "Volume_hot.png"
ren "Warning.png" "Warning_hot.png"
ren "Waste Bin.png" "Waste_Bin_hot.png"
ren "Window-Add.png" "Window_Add_hot.png"
ren "Window-Bring To Front.png" "Window_Bring_To_Front_hot.png"
ren "Window-Cascade.png" "Window_Cascade_hot.png"
ren "Window-Close.png" "Window_Close_hot.png"
ren "Window-Delete.png" "Window_Delete_hot.png"
ren "Window-Edit.png" "Window_Edit_hot.png"
ren "Window-Maximise.png" "Window_Maximise_hot.png"
ren "Window-Minimise.png" "Window_Minimise_hot.png"
ren "Window-New.png" "Window_New_hot.png"
ren "Window-Next.png" "Window_Next_hot.png"
ren "Window-Options.png" "Window_Options_hot.png"
ren "Window-Preview.png" "Window_Preview_hot.png"
ren "Window-Previous.png" "Window_Previous_hot.png"
ren "Window-Properties.png" "Window_Properties_hot.png"
ren "Window-Remove.png" "Window_Remove_hot.png"
ren "Window-Search.png" "Window_Search_hot.png"
ren "Window-Send To Back.png" "Window_Send_To_Back_hot.png"
ren "Window-Split.png" "Window_Split_hot.png"
ren "Window-Tile Horizontal.png" "Window_Tile_Horizontal_hot.png"
ren "Window-Tile Vertical.png" "Window_Tile_Vertical_hot.png"
ren "Window.png" "Window_hot.png"
ren "Wizard.png" "Wizard_hot.png"
ren "Word Count.png" "Word_Count_hot.png"
ren "Word Wrap-2.png" "Word_Wrap_2_hot.png"
ren "Word Wrap.png" "Word_Wrap_hot.png"
ren "Work Sheet-Auto Format.png" "Work_Sheet_Auto_Format_hot.png"
ren "Work Sheet-Delete.png" "Work_Sheet_Delete_hot.png"
ren "Work Sheet-New.png" "Work_Sheet_New_hot.png"
ren "Work Sheet-Options.png" "Work_Sheet_Options_hot.png"
ren "Work Sheet-Protect.png" "Work_Sheet_Protect_hot.png"
ren "Work Sheet-Rename.png" "Work_Sheet_Rename_hot.png"
ren "Work Sheet.png" "Work_Sheet_hot.png"
ren "Zoom-In.png" "Zoom_In_hot.png"
ren "Zoom-Out.png" "Zoom_Out_hot.png"
